theme = "nord-night"

[editor]
line-number = "absolute"
scroll-lines = 1
auto-pairs = false
mouse = true
bufferline = "always"
color-modes = true
# auto-format = true

[editor.cursor-shape]
insert = "bar"
# normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert]
j = { k = "normal_mode" }

[keys.normal]
p = "paste_clipboard_before"
y = "yank_main_selection_to_clipboard"
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
S-A-down = ["normal_mode", "extend_to_line_bounds", "yank", "open_below", "replace_with_yanked", "collapse_selection"]
S-A-up = ["normal_mode", "extend_to_line_bounds", "yank", "open_above", "replace_with_yanked", "collapse_selection"]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["version-control", "diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = ""
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
character = "|"
skip-levels = 1
